### ISSUE TITLE
[suggest] inputId in input_task_button 

### ISSUE THREAD

**Issue by jhk0530** [rstudio/bslib#1034]
Hi, thanks for newly updated feature `input_task_button`, and I really love it. 

I'm not sure this is good or not, but just this is suggestion.

## situation

I felt a little awkward during change my previous `actionButtons` with `input_task_button`

`actionButton` of **shiny** requires `inputId`, `label`, `icon`, `width`, `disabled` as parameter

However `input_task_button` which may replace with `actionButton` has parameter

`id`, `label`, `icon`, `label_busy`, `icon_busy`, `type`, `auto_reset` as parameter.

Most of work may done by change `actionButton(` as `input_task_button(` but not id. 
I understand `inputId` and `id` has similar purpose and it seems if i change inputId as id works properly.

## suggestion

Actually I don't know the context that specify it as an `id` rather than an `inputId`.

but if `input_task_button` provides `inputId` as pameter which works as `id` like below, it also good for shiny users who wants **update** `actionButton` as `input_task_button` like me.

use `inputId` as default pameter, but also providing `id` works as now.

## example

``` r
input_task_button <- function (inputId, id = inputId, label, ...){
...
}
```
if it seems fine. I 'll try to make PR with this.

Thanks ! 

Again, thanks for update bslib.

**Comment by gadenbuie** [comment]
I'd recommend providing the input ID to both `actionButton()` and `input_task_button()` without naming the parameter, i.e.

```r
actionButton("go")
input_task_button("go")
```

We're committed to making the first argument of any `input_*()` function the `id`, unless `id` isn't required as in `input_dark_mode()`, but we prefer `id` in new input and output functions.

Thanks for your suggestion -- it's certainly a reasonable idea -- but it would clutter the `input_task_button()` API and require us to make a breaking change at some point. Since you're likely only changing one or two `actionButton()` inputs at a time, you'll already be manually updating the functions and can remove the `inputId =` if you want to switch back and forth.
