### ISSUE TITLE
Ordering of variables in bs_theme()

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#1142]
``` r
library(bslib)
#> 
#> Attaching package: 'bslib'
#> The following object is masked from 'package:utils':
#> 
#>     page

bs_theme(
  primary = "red",
  navbar_bg = "$primary"
) |>
  sass::as_sass() |>
  # show just the relevant lines for this reprex
  as.character() |>
  strsplit("\n") |>
  (\(x) x[[1]][3:5])()
#> [1] "$navbar_bg: $primary !default;" ""                              
#> [3] "$primary: #FF0000 !default;"
```

<sup>Created on 2024-12-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by gadenbuie** [comment]
I see, this happens because `...` comes before `primary` here
 https://github.com/rstudio/bslib/blob/74a138c93568221bac32cd269ab336a3e665bb21/R/bs-theme.R#L173-L186

I'm guessing that's there to enable syntax like this:

```r
bs_theme(
  blue = "#0000ff",
  primary = "$blue"
)
```

Alternatively, the other way around this is

``` r
bs_theme(navbar_bg = "$primary") |> bs_add_variables(primary = "red")
#> $primary: red !default;
#> $navbar_bg: $primary !default;
```

**Comment by cpsievert** [comment]
IIRC, the thinking is more along the lines of:

1. Formal (named) arguments have a 1-to-potentially many Sass variable mapping. These should come as the 1st layer of defaults since they are the 1st and primary way to customize.
2. Other variable definitions (`...`) should come as the 2nd layer of defaults since they should be allowed to overrule (1). And, since they are the 2nd layer, they get hoisted to the top.

The drawback to this approach is that, as you've highlighted here, you can't have "downstream" variable defaults reference "upstream" variables since they are defined yet. The main mechanism we added to workaround this problem is `bs_add_variables(.where = "declarations")`:

```r
bs_theme(primary = "red") |>
  bs_add_variables("navbar-bg" = "$primary", .where = "declarations")
```
