### ISSUE TITLE
Add support for shinydashboard

### ISSUE THREAD

**Issue by giadasp** [rstudio/bslib#310]
I really like your package but I saw that it does not work for the dashboardPage of shinydashboard.
Are you thinking to extend the package also for that?
It would be very helpful!
Thank you

Giada

**Comment by aleonti** [comment]
Adding to this issue - I am able to use `bslib::bs_theme()` from a module that is called in my shinydashboard, but it seems to break some components of the dashboard. Text sizes are very inconsistent across the dashboard (dropdown menu text & tab text is large, text beside radio buttons and checkboxes is unreadably small), and the dashboard bar across the top of the page becomes disjointed and very wide. I'm assuming this is because the themes are not designed/optimized for use with a Shiny dashboard?

**Comment by chrisbrownlie** [comment]
Just adding a comment here for information for anyone in future, as I originally had the same (slightly naive) question. {shinydashboard} uses AdminLTE v2 which uses Bootstrap 3, so newer versions of Bootstrap - e.g. the default for `bslib::bs_theme()` - are not compatible with {shinydashboard}.

i.e. see the note at the [top of this page.](http://rstudio.github.io/shinydashboard/appearance.html)

**Comment by cpsievert** [comment]
The next upcoming release (0.5.0) takes a significant step towards providing a new toolkit for creating dashboards. See the new getting started article to learn more https://rstudio.github.io/bslib/articles/dashboards.html

Also, if you feel like there is anything critical that `{shinydashboard}` provides that `{bslib}` doesn't (yet) provide, please let us know!

**Comment by cpsievert** [comment]
Actually, instead of continuing this discussion in an issue thread, I'd like to welcome everyone to contribution here https://github.com/rstudio/bslib/discussions/618 


(Closing this issue since we likely won't be aiming to support `{shinydashboard}`, but instead supersede it)
