### ISSUE TITLE
Doesn't work fluidRow with  align = "center" with textOutput

### ISSUE THREAD

**Issue by apalacio10** [rstudio/bslib#343]
Hi there !

The fluidRow function with the align center parameter has no effect on a textOutput using version 4

`fluidRow(textOutput(outputId="test"),align = "center")`

**Comment by cpsievert** [comment]
I'd consider `align="center"` an "off-label" usage of `fluidRow()` that just happened to work in Bootstrap 3 because of how the `.row` class was implemented. In Bootstrap 4+, `.row` is now based on [CSS flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/), which is why `align="center"` no longer works in the way you're expecting, but you should be able to change `align="center"` to `style = "justify-content: center"`. Here's a full example:

```r
library(shiny)

ui <- fluidPage(
  theme = bslib::bs_theme(),
  fluidRow(
    textOutput("test"),
    style = "justify-content: center"
  )
)

server <- function(input, output, session) {
  output$test <- renderText("test")
}

shinyApp(ui, server)
```

**Comment by apalacio10** [comment]
Thanks for the explanation
