### ISSUE TITLE
Bslib doesn't work correctly with uiOput in some case 

### ISSUE THREAD

**Issue by apalacio10** [rstudio/bslib#344]
Hello,

When using the cran version and a user interface is defined as bootstrapPage with a theme and uiOutput with a fluidPage inside, the content within the fluidPage knows the theme defined in the bootstrapPage. However, in the developer version that doesn't happen.

For example, we expect to have selectizeInput and its appearance should be.

![imagen](https://user-images.githubusercontent.com/40868159/123522897-2040a000-d686-11eb-81e9-ad2d7df0ed9a.png)

But as a result we get 

![imagen](https://user-images.githubusercontent.com/40868159/123522878-02733b00-d686-11eb-911f-8c85a7a9a0f2.png)

It's important that this happens using version 4 and 5 

```
library(shiny)

theme <- bslib::bs_theme(version = 4,bootswatch = "cyborg",bg="#323232",fg="#FFFFFF","body-bg"="#323232",primary = "#002860",
                         secondary  = "#6E6E6E",success = "#02A502",info="#00AADD",warning = "#FA9300",danger = "#F0302B","input-border-color"="#000000",
                         base_font = "Helvetica Neue",heading_font = "Helvetica Neue")

ui <- bootstrapPage(theme = theme,

    uiOutput("test")
)

server <- function(input, output) {

    output$test <- renderUI({
       fluidPage(
                selectizeInput("bins",
                            "Number of bins:",
                            choices=c(1,2,3,4,5))
       )
           
    })

}

shinyApp(ui = ui, server = server)
```

**Comment by cpsievert** [comment]
As a general rule, you shouldn't use dynamic UI (i.e., `renderUI()`) to return a page layout (e.g., `fluidPage()`, `navbarPage()`, etc)...I'm pretty sure we'd consider any such example that happens to work to be an ["off-label"](https://www.rstudio.com/resources/rstudioglobal-2021/maintaining-the-house-the-tidyverse-built/) usage. That said, if you can think of a "valid" use-case for returning a page layout via dynamic UI, please let me know! 

Also, to be clear, if you remove the `fluidPage()` in your example, you get the expected behavior.
