### ISSUE TITLE
Doesn't work nav-tabs-link-active-bg

### ISSUE THREAD

**Issue by apalacio10** [rstudio/bslib#346]
Hello,

I'm not sure if it's a issue, but with bootswatch cyborg it's not possible to set background color in nav-tabs-link-active.  That happens with version 4 and 5 

`library(shiny)

# Main app UI
ui <- fluidPage(theme =  bslib::bs_theme(version = 4,bootswatch = "cyborg","nav-tabs-link-active-bg"="#FA9300","nav-tabs-border-color"="#FA9300",
                                         "nav-tabs-link-active-border-color"="#FA9300"),
                tabsetPanel(
                    tabPanel("One", "No padding"),
                    tabPanel("Two", "Very sad!")
                ))

# Main app server
server <- function(input, output, session) {

}

shinyApp(ui, server)`

**Comment by cpsievert** [comment]
Unfortunately Bootstrap Sass variables aren't guaranteed to work well with Bootswatch themes since Bootswatch themes often add additional CSS rules that either conflict with, or simply don't listen to Bootstrap Sass variables. 

To put it another way, if you're wanting to customize a Bootswatch theme, you're likely going to want to add [additional rules](https://rstudio.github.io/bslib/articles/bslib.html#add-rules) instead of [setting Bootstrap Sass variables](https://rstudio.github.io/bslib/articles/bslib.html#everything-else).
