### ISSUE TITLE
custom color for <pre> <code> <span> tags

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [rstudio/bslib#427]
Hello, 

I searched issues for similar topic.

My request is to allow custom colors for the `<pre>`, `<code>` and `<span>` tags, as every Overall theme changes the `fg` and `bg` colors nicely but the issue is `library(ggplot2)` is *always red* regardless of the theme. 

<img width="419" alt="Screen Shot 2022-05-02 at 2 37 19 PM" src="https://user-images.githubusercontent.com/55933131/166323572-adb91ffa-3853-434e-91a3-a1f6a7e45181.png">

I have tried to change these tag colors in my YAML section of my Rmd file. 

<img width="652" alt="Screen Shot 2022-05-02 at 2 37 56 PM" src="https://user-images.githubusercontent.com/55933131/166323681-db80e99b-3d57-41d8-8ee5-3333405201ed.png">

I know that the specific tag in the code is `<span class="hljs-keyword">library(ggplot)</span>` which is always red.

It would be really appreciated if we could have a more readable color while having dark themed Rmd files. Thank you.

**Comment by cpsievert** [comment]
bslib does provide some Sass vars for theming "non-syntax highlighted" code

<img width="916" alt="Screen Shot 2022-06-07 at 10 14 43 AM" src="https://user-images.githubusercontent.com/1365941/172417271-a3c4bc01-dcaa-451d-8459-1ca42ff6dbc9.png">


You can prevent syntax highlighting by putting `highlight: null` in the YAML header. 

Since there is already issue about making pandoc's syntax highlighting better respect bslib themes (it seems this is probably what you want), I'm gonna close this issue  

https://github.com/rstudio/bslib/issues/145

**Comment by PythonCoderUnicorn** [comment]
yes, thank you. It worked.

<img width="651" alt="Screen Shot 2022-06-07 at 9 38 02 AM" src="https://user-images.githubusercontent.com/55933131/172422489-94cb0394-d8f0-4062-98f2-16df5b11c9c5.png">
