### ISSUE TITLE
Inline radio / checkboxes are missing spacing

### ISSUE THREAD

**Issue by schloerke** [rstudio/bslib#556]
Using the current bslib ([dc27605](https://github.com/rstudio/bslib/commit/dc27605db716afbcf39cdfa9aa0f9933e11c3fbd)), inline checkbox groups and radio buttons have had their spacing reduced.

Using a simple python app with the latest bslib + bs5:

```python
from shiny import App, ui
app_ui = ui.page_fluid(
    ui.input_radio_buttons("rb", "Choose one:", ["one", "two"], inline=True),
)
app = App(app_ui, None)
```

#### Before:

![image (1)](https://user-images.githubusercontent.com/93231/234682829-80b28491-945e-48fa-aa8d-3f2aaab0db08.png)

![image (3)](https://user-images.githubusercontent.com/93231/234682824-de6cedeb-6063-48c4-aa77-fecd4b17b4c8.png)

#### After:

![image](https://user-images.githubusercontent.com/93231/234682831-ee168b79-6456-4296-9856-f6a2a08a1ffa.png)

![image (2)](https://user-images.githubusercontent.com/93231/234682827-116ceec7-c19b-47d7-a2b9-15533e905a7c.png)

----------------------

Ideally, fixing the CSS is the best option. 

Currently in `py-shiny`, I can get around this by added `_add_ws=TRUE` in https://github.com/rstudio/py-shiny/blob/4c075fd2/shiny/ui/_input_check_radio.py#L343

cc @wch

**Comment by cpsievert** [comment]
I could be wrong, but I don’t think it’s bslib’s problem to fix. It’s not a problem in R since R always emits whitespace (PyShiny’s default tag writing logic is more aggressive about not adding whitespace, which is why the _add_ws  was needed in this case). I suppose we could add some CSS margin  and never include whitespace, but that’d require more changes for effectively the same result
