### ISSUE TITLE
Auto-adjustable height of value_box with DT table

### ISSUE THREAD

**Issue by philiph99** [rstudio/bslib#626]
When using value_box with DT::dataTableOutput, the value_box is way too large if only a few rows are displayed.

Is it possible to make value_box()'s height automatically adjust to the size of DT::dataTableOutput()?

I wrote an example to display the issue:
```
library(shiny)
library(DT)
library(bslib)

ui <- fluidPage(
  theme = bs_theme(
    secondary = "#CCCCCB", bootswatch = "flatly"
  ),
  numericInput(
    inputId = "number", 
    label = "Number of rows in table below", 
    min = 1, max = 10, value = 3
  ),
  bslib::value_box(
    title = "value box", 
    theme_color = "secondary",
    value = DT::dataTableOutput("table"),
    p(icon("pen-to-square"), "To edit a systemic therapy entry, click the respective row in the table")
  )
)

server <- function(input, output) {
  
  observeEvent(req(input$number), {
    
  output$table <- DT::renderDataTable({
    
    DT::datatable(iris[1:input$number,], 
                  fillContainer = TRUE,
                  options = list(dom = 't'))
    })
  })
}

shinyApp(ui, server)
```
By setting DT::datatable(, fill_container = TRUE), the table is scrollable, but the user will not know if more rows exist than are being displayed and whether he/she will have to scroll down. Therefore, I do not just want to make the value_box()'s height very small.

**Comment by gadenbuie** [comment]
Hi @philiph99! One thing that makes it hard to directly answer your question is that often the height of value boxes and cards are dependent upon a number of other factors: primarily the containing layout and the screen size. Could you describe the layout of your app or share a screenshot of it? That would help me give a better answer.

That said, you might want to try using a `card()` instead of a `value_box()` in this situation. First of all, I think you're likely to get unusual behavior by making the DT table the `value` of your `value_box()` – especially with v0.5.0 of bslib.

Instead, you might want to try using a `card()`, like this:

```r
card(
  max_height = 400,  # <1>
  card_header("My Table"),
  card_body(
    height = "auto",
    fillable = FALSE, # <2>
    DT::dataTableOutput("table") # <3>
  ),
  card_footer(
   icon("pen-to-square"),
   "To edit a systemic therapy entry, click the respective row in the table"
  )
)
```

and in the server function, you can remove `fillContainer = TRUE` from the `DT::datatable()` call.

Adding this to your app gives me a card that looks like this.

![image](https://github.com/rstudio/bslib/assets/5420529/da8feb9b-da46-4378-a7bf-1ff7ad7980db)

I left `<#>` comments in the code above to call out some of the settings I changed.

1. First, I used `max_height = 400` on the `card()` to limit the card to a total of 400px tall. In this layout, at least, where the card isn't in a fillable container, this becomes the primary restriction on its height: it can grow until it hits 400px.

2. I explicitly used `card_body()` with `fillable = FALSE`. This makes the height of the card body area depend on the contents within it. Now both the card body and the card itself will have a height dependent on the stuff inside the card body, but the card won't be allowed to grow taller than 400px.

3. Finally, I needed to turn off `fillContainer = TRUE` in `DT::datatable()`. This appears to prioritize the body of the table rather than the overall height of the table. Without this argument the table body will height is driven by its contents, especially because its not in a fillable container thanks to (2).

Here's your full example app, with a small amount of refactoring.


```r
library(shiny)
library(DT)
library(bslib)

ui <- fluidPage(
  theme = bs_theme(
    secondary = "#CCCCCB", bootswatch = "flatly"
  ),
  numericInput(
    inputId = "number",
    label = "Number of rows in table below",
    min = 1, max = 10, value = 3
  ),
  card(
    max_height = 400,
    card_header("My Table"),
    card_body(
      height = "auto",
      fillable = FALSE,
      DT::dataTableOutput("table")
    ),
    card_footer(
     icon("pen-to-square"),
     "To edit a systemic therapy entry, click the respective row in the table"
    )
  )
)

server <- function(input, output) {

  my_dt_table <- reactive({
    DT::datatable(
      iris[1:input$number, ],
      options = list(dom = "t")
    )
  })

  output$table <- DT::renderDataTable(my_dt_table())
}

shinyApp(ui, server)
```

**Comment by philiph99** [comment]
Hi @gadenbuie 

That's fantastic and exactly what I want! Thank you!

 Is there any way to add a background color to card_header(), card_body() and card_footer()?

**Comment by gadenbuie** [comment]
Awesome! And, yes you can! Add `class = "text-bg-secondary"` to the `card()` call. It's a new class in BS 5.2 that sets both the background color of the card and the text color. There are other classes for the the rest of the primary, info, warning, etc colors: https://getbootstrap.com/docs/5.3/components/card/

**Comment by philiph99** [comment]
Perfect! Thank you! All works well now 👍
