### ISSUE TITLE
Slider handle is in wrong location in Crosstalk example 

### ISSUE THREAD

**Issue by wch** [rstudio/bslib#813]
On this page https://rstudio.github.io/bslib/articles/any-project/

The slider looks like this:

<img width="423" alt="image" src="https://github.com/rstudio/bslib/assets/86978/95550016-ca54-452b-8490-87622583217e">

This is probably related to https://github.com/rstudio/shiny/issues/3905.

**Comment by gadenbuie** [comment]
The key problem here appears to be that we're getting the compiled `ion.rangeSlider.css` file from Shiny rather than the dynamic dependency that involves the Sass compilation step (see https://github.com/rstudio/shiny/blob/a6fc6bf8cb5032138fb33327d07ad0f4e19c9f86/R/input-slider.R#L225-L235)

The result is that we're missing the effects of the Sass variables that are set in the shiny preset for ionrangeslider https://github.com/rstudio/bslib/blob/ad946cafdbf1c91cfd714cb39948bb203ae66e66/inst/builtin/bs5/shiny/ionrangeslider/_variables.scss#L1-L7

I think part of this regression might be an inadvertent side-effect of moving from opting into the shiny preset to having it be the default.

@cpsievert Any ideas about how to proceed?

**Comment by gadenbuie** [comment]
Specifically, in the deferred dependency evaluation, `bs_global_get()` returns `NULL` for `preset = "shiny"` here

https://github.com/rstudio/bslib/blob/ad946cafdbf1c91cfd714cb39948bb203ae66e66/R/bs-dependencies.R#L345-L346

but the styles are fixed by adding these lines to the example app

```r
theme <- bs_theme(5, preset = "shiny")
bs_global_set(theme)
```

**Comment by cpsievert** [comment]
> Any ideas about how to proceed?

Ideally we'd solve this (as well as other issues) by generally allowing `bs_dependency_defer()` to pick up on the `theme` correctly when statically rendered. A long time ago I had looked into doing this (via https://github.com/rstudio/htmltools/pull/267), but I can't remember exactly why we dropped it (other than it being a difficult thing to get right). Also, even if we did solve this problem, it wouldn't improve the equivalent Quarto scenario, so in the short term, I'm leaning towards either: (1) making these styling changes via rules (not variables) or (2) updating the ionrangeslider sass to make use of CSS variables (and having the preset change the defaults). Definitely in the long term, it would make sense to do 2, but it's also not ideal for us to now require a new version of shiny to get the better looking slider.

**Comment by gadenbuie** [comment]
I'd rather solve the problem of `bs_dependency_defer()` not resolving the correct `theme` value when statically rendered. I wonder if the problem might get easier if we thought of it not as a general problem that needs to be solved in the abstract for any `tag()` or `tagList()`, but a problem specific to the `page_*()` functions in bslib (where `theme` is set)?

**Comment by gadenbuie** [comment]
#815 has a proposal for temporarily setting the global theme during render via the `bslib_page` objects returned by our `page_*()` functions.
