### ISSUE TITLE
Unable to open a newly inserted accordion panel 

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#872]
This issue was introduced by `Shiny.renderContent()` becoming async (in https://github.com/rstudio/shiny/pull/3904).

In hindsight, it's quite obviously a bad idea for `Shiny.renderContent()` to always be async since, with any `insert`-like operation, users are going to expect that the operation to have finished before the next line of R code happens. Here's an example of that:

<details>
<pre><code>app.R</code></pre>

```r

remotes::install_github("rstudio/shiny")

library(bslib)
library(shiny)

ui <- page_fixed(
  accordion(
    id = "acc", multiple = TRUE,
    accordion_panel("A", "a"),
    accordion_panel("B", "b")
  )
)

server <- function(input, output) {
  
  observe({
    # Triggers a Shiny.renderContent()
    accordion_panel_insert(
      "acc", accordion_panel("C", "c")
    )
    # Relies on the content being rendered
    accordion_panel_open("acc", "C")
  })
  
}

shinyApp(ui, server)
```
</details>

Going forward, it seems like it'd be a lot better to revert [changes made to `srcts/src/shiny/render.ts`](https://github.com/rstudio/shiny/pull/3904/files#diff-7aa61053d5a807425314d89085e38603c93b1c63a841d378e279aa3cd70417de
) (except for the `await`s in `renderContentAsync()`).

**Comment by wch** [comment]
Changing `Shiny.renderContent()` back to sync is problematic because it won't work with shinylive on Chrome. (More info at https://github.com/rstudio/shiny/pull/3929#issuecomment-1783917762)

I think what we can do is:
- Change Shiny's `InputBinding.receiveMessage` so that it can be sync or async (similar to [`OutputBinding.renderValue`](https://github.com/rstudio/shiny/blob/77bc4e9ec72e97a25f64134ba981d8b2e9cb5895/srcts/src/bindings/output/outputBinding.ts#L14))
- Change all the uses of `Shiny.renderContent()` in bslib to use `await`.
