### ISSUE TITLE
Dynamic creation of grid cards not working in bslib

### ISSUE THREAD

**Issue by benubah** [rstudio/bslib#935]
## Describe the problem
In `shinydashboard` it is straightforward to dynamically create grid boxes in two column-formats as in the reprex below:

```r
library(shiny)
library(bslib)

ui <- navbarPage(
  title = "My App",
  bg = "#0062cc",
  tabPanel(title = "One", uiOutput("mycards")),
)

server <- function(input, output) {
  output$mycards <- renderUI({
    p <- lapply(1:6, function(a) {
      chart_name <- paste0("chart_", a)
      output[[chart_name]] <- renderPlot({
        mtcars |>
          head() |>
          plot()
      })
      shinydashboard::box(
        title = chart_name,
        width = 6,
            plotOutput(chart_name)
      )
    })
  })
}
shinyApp(ui, server)
```

This does not work in `bslib` as well. `bslib` creates one card per row regardless of specifying a `layout_column` of `1/2`:

```r
library(shiny)
library(bslib)

ui <- page_navbar(
  title = "My App",
  bg = "#0062cc",
  nav_panel(title = "One",
            layout_column_wrap(
              width = 1/2,
              uiOutput("mycards")
            )
        )
)

server <- function(input, output) {
  output$mycards <- renderUI({
    p <- lapply(1:6, function(a) {
      chart_name <- paste0("chart_", a)
      output[[chart_name]] <- renderPlot({
        mtcars |>
          head() |>
          plot()
      })
            bslib::card(
              height = 500,
              style = "resize:vertical;",
              full_screen = TRUE,
              card_header(class = "bg-dark", chart_name),
              card_body(
                min_height = 500,
                plotOutput(chart_name)
              )
            )
    })
  })
}
shinyApp(ui, server)
```

**Comment by gadenbuie** [comment]
When you use `uiOutput()` inside `layout_columns()`, like this,

```r
# ui...
layout_columns(
  uiOutput("my_cards")
)

# server...
output$my_cards <- renderUI({
  lapply(1:6, card())
}}
```

the `uiOutput()` is a single element and all of the items returned by that output are children of the `uiOutput()` container. In other words, you've given a single element to `layout_columns()` and that single element happens to have 6 elements inside it.

The fix is to move the `layout_columns()` into the `renderUI()` on the server size:

```r
# ui...
uiOutput("my_cards")

# server...
output$my_cards <- renderUI({
  layout_columns(
    !!!lapply(1:6, card())
  )
})
```

Note that we've used the [rlang splice operator `!!!`](https://rlang.r-lib.org/reference/splice-operator.html) to inject the list of cards as direct arguments of `layout_columns()`. This makes each card in the list a direct child of `layout_columns()` and will give you the layout you want.

I used `layout_columns()` in my examples, but the same idea applies to `layout_column_wrap()`.

**Comment by benubah** [comment]
Thanks! This works with `layout_column_wrap` for my use-case - gives me two cards per row.

But replacing with `layout_columns` produces:

![image](https://github.com/rstudio/bslib/assets/11357251/dad23981-efcf-4702-866c-6cc5e039614b)

**Comment by gadenbuie** [comment]
Yeah, `layout_columns()` has a different mechanism for helping you layout the elements that is based on [Bootstrap's 12 column grid](https://getbootstrap.com/docs/5.3/layout/css-grid/). If you want two cards per row, you can set `col_widths = 6` (6 column units per item). Another advantage of `layout_columns()` is that you can choose the column widths at different breakpoints, so you could set `col_widths = breakpoints(md = 6, lg = 4, xl = 3)` to have 2, 3, and 4 items per row at medium, large, and extra-large screen sizes.

That said, if you get what you're looking for with `layout_column_wrap()`, by all means stick with it!

**Comment by benubah** [comment]
Thanks a bunch! This resolves it all
